name = "DLFP8"
uuid = "f4c16678-4a16-415b-82ef-ed337c5d6c7c"
authors = ["chengchingwen <chengchingwen214@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
